language: python
sudo: false
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
before_install:
    - "wget https://s3.amazonaws.com/textblob/nltk_data-0.11.0.tar.gz"
    - "tar -xzvf nltk_data-0.11.0.tar.gz -C ~"
# Install dependencies
install:
    - "pip install numpy"
    - "pip install -U ."
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -r docs/requirements.txt; fi
# Run tests
script:
    - "python run_tests.py"
    # Run doctests against py34
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then cd docs && make doctest; fi
